### PR TITLE
Adds upgrade charm event handler

### PR DESCRIPTION
**Pull request by claudiubelu**
When upgrading the charm, the charm remains in a Waiting Status because the charm is only set to Active when the mongodb relation gets updates valid data.

This commit adds an upgrade charm handle, which will ensure that the charm status will be set appropriately.

### CODE REVIEW

**Comment by claudiubelu** [comment]
Depends On: https://github.com/finos/legend-juju-db-operator/pull/8

**Comment by jnsgruk** [comment]
Looks good - modulo the failing lint check :)

**Comment by jnsgruk** [comment]
@claudiubelu this seems to be in conflict now?

**Comment by claudiubelu** [comment]
> 

Rebased.

**Pull request merged**
